// Generated by tools/export_character_sprites.py.
pub(super) const DATA: SpriteData = SpriteData {
    idle: &[include_bytes!("idle_00.png"), include_bytes!("idle_01.png"), include_bytes!("idle_02.png"), include_bytes!("idle_03.png"), include_bytes!("idle_04.png"), include_bytes!("idle_05.png"), include_bytes!("idle_06.png"), include_bytes!("idle_07.png"), include_bytes!("idle_08.png"), include_bytes!("idle_09.png"), include_bytes!("idle_10.png"), include_bytes!("idle_11.png")],
    run: &[include_bytes!("run_00.png"), include_bytes!("run_01.png"), include_bytes!("run_02.png"), include_bytes!("run_03.png"), include_bytes!("run_04.png"), include_bytes!("run_05.png"), include_bytes!("run_06.png"), include_bytes!("run_07.png"), include_bytes!("run_08.png"), include_bytes!("run_09.png"), include_bytes!("run_10.png"), include_bytes!("run_11.png"), include_bytes!("run_12.png"), include_bytes!("run_13.png"), include_bytes!("run_14.png"), include_bytes!("run_15.png")],
    attack: &[include_bytes!("attack_00.png"), include_bytes!("attack_01.png"), include_bytes!("attack_02.png"), include_bytes!("attack_03.png"), include_bytes!("attack_04.png"), include_bytes!("attack_05.png"), include_bytes!("attack_06.png"), include_bytes!("attack_07.png"), include_bytes!("attack_08.png"), include_bytes!("attack_09.png"), include_bytes!("attack_10.png"), include_bytes!("attack_11.png"), include_bytes!("attack_12.png"), include_bytes!("attack_13.png"), include_bytes!("attack_14.png"), include_bytes!("attack_15.png"), include_bytes!("attack_16.png"), include_bytes!("attack_17.png"), include_bytes!("attack_18.png"), include_bytes!("attack_19.png")],
    canvas_height_ratio: 1.397836,
    stride_height_ratio: 0.82846,
    run_seconds: 1.066667,
    attack_seconds: 1.2,
    hit_fraction: 0.5833333,
    idle_seconds: 2.0,
    pixels: 192,
    anchor: [0.3521938, 0.9432908],
    attack_times: &[0.0, 0.05555556, 0.1111111, 0.1666667, 0.2222222, 0.2777778, 0.3333333, 0.3888889, 0.4444444, 0.5, 0.5555556, 0.5833333, 0.6111111, 0.6666667, 0.7222222, 0.7777778, 0.8333333, 0.8888889, 0.9444444, 1.0],
};
