// Generated by tools/export_forest_sprites.py; do not edit by hand.
const MAP_WIDTH: f32 = 2400.0;
const MAP_HEIGHT: f32 = 540.0;
const TILE_WIDTH: f32 = 800.0;
const BLEED: f32 = 1.0;
const TILE_PNG: [&[u8]; 3] = [
    include_bytes!("tile_00.png"),
    include_bytes!("tile_01.png"),
    include_bytes!("tile_02.png"),
];
