// Generated by tools/export_character_sprites.py.
pub(super) const DATA: SpriteData = SpriteData {
    idle: &[include_bytes!("idle_00.png")],
    run: &[include_bytes!("run_00.png"), include_bytes!("run_01.png"), include_bytes!("run_02.png"), include_bytes!("run_03.png"), include_bytes!("run_04.png"), include_bytes!("run_05.png"), include_bytes!("run_06.png"), include_bytes!("run_07.png"), include_bytes!("run_08.png"), include_bytes!("run_09.png"), include_bytes!("run_10.png"), include_bytes!("run_11.png"), include_bytes!("run_12.png"), include_bytes!("run_13.png"), include_bytes!("run_14.png"), include_bytes!("run_15.png")],
    attack: &[include_bytes!("attack_00.png"), include_bytes!("attack_01.png"), include_bytes!("attack_02.png"), include_bytes!("attack_03.png"), include_bytes!("attack_04.png"), include_bytes!("attack_05.png"), include_bytes!("attack_06.png"), include_bytes!("attack_07.png"), include_bytes!("attack_08.png"), include_bytes!("attack_09.png"), include_bytes!("attack_10.png"), include_bytes!("attack_11.png"), include_bytes!("attack_12.png"), include_bytes!("attack_13.png"), include_bytes!("attack_14.png"), include_bytes!("attack_15.png"), include_bytes!("attack_16.png"), include_bytes!("attack_17.png"), include_bytes!("attack_18.png"), include_bytes!("attack_19.png"), include_bytes!("attack_20.png"), include_bytes!("attack_21.png")],
    canvas_height_ratio: 1.242015,
    stride_height_ratio: 0.352602,
    run_seconds: 1.066667,
    attack_seconds: 1.4,
    hit_fraction: 0.5238095,
    idle_seconds: 1.0,
    pixels: 192,
    anchor: [0.3807157, 0.9458369],
    attack_times: &[0.0, 0.04761905, 0.0952381, 0.1428571, 0.1904762, 0.2380952, 0.2857143, 0.3333333, 0.3809524, 0.4285714, 0.4761905, 0.5238095, 0.5714286, 0.6190476, 0.6666667, 0.7142857, 0.7619048, 0.8095238, 0.8571429, 0.9047619, 0.952381, 1.0],
};
