// Generated by tools/export_character_sprites.py.
pub(super) const DATA: SpriteData = SpriteData {
    idle: &[include_bytes!("idle_00.png")],
    run: &[include_bytes!("run_00.png"), include_bytes!("run_01.png"), include_bytes!("run_02.png"), include_bytes!("run_03.png"), include_bytes!("run_04.png"), include_bytes!("run_05.png"), include_bytes!("run_06.png"), include_bytes!("run_07.png"), include_bytes!("run_08.png"), include_bytes!("run_09.png"), include_bytes!("run_10.png"), include_bytes!("run_11.png")],
    attack: &[include_bytes!("attack_00.png"), include_bytes!("attack_01.png"), include_bytes!("attack_02.png"), include_bytes!("attack_03.png"), include_bytes!("attack_04.png"), include_bytes!("attack_05.png"), include_bytes!("attack_06.png"), include_bytes!("attack_07.png"), include_bytes!("attack_08.png"), include_bytes!("attack_09.png"), include_bytes!("attack_10.png"), include_bytes!("attack_11.png"), include_bytes!("attack_12.png"), include_bytes!("attack_13.png")],
    canvas_height_ratio: 1.116875,
    stride_height_ratio: 0.5799803,
    run_seconds: 0.8,
    attack_seconds: 0.8,
    hit_fraction: 0.4583333,
    idle_seconds: 1.0,
    pixels: 192,
    anchor: [0.3173772, 0.9464285],
    attack_times: &[0.0, 0.08333333, 0.1666667, 0.25, 0.3333333, 0.4166667, 0.4583333, 0.5, 0.5833333, 0.6666667, 0.75, 0.8333333, 0.9166667, 1.0],
};
