[workspace]
resolver = "2"

[profile.release]
lto = true
codegen-units = 1
panic = "abort"
strip = true

[package]
name = "shooter"
version = "0.1.0"
edition = "2024"
publish = false

[package.metadata.game]
title = "Shooter"
description = "A high-octane twin-stick arena shooter demonstrating manual entity management, collision handling, and a custom particle engine."
tags = ["Physics", "Particles", "Top-Down"]

[package.metadata.android.sdk]
min_sdk_version = 26

[lib]
crate-type = ["cdylib", "staticlib", "rlib"]

[dependencies]
# Internal crates
redixel = { path = "../../crates/redixel", features = ["audio"] }

# External crates
log = "0.4"
