// Generated by tools/export_goblin_sprites.py; do not edit by hand.
const FRAME_PIXELS: f32 = 256.0;
const RUN_CYCLE_SECONDS: f32 = 0.8;
pub(super) const ATTACK_SECONDS: f32 = 0.3;
pub(super) const ATTACK_HIT_FRACTION: f32 = 0.4444444;
const GROUND_SPEED_PIXELS: f32 = 169.6856;
const ANCHOR_UV: [f32; 2] = [0.4999999, 0.957143];
const IDLE_PNG: &[u8] = include_bytes!("idle.png");
const RUN_PNG: [&[u8]; 24] = [
    include_bytes!("run_00.png"),
    include_bytes!("run_01.png"),
    include_bytes!("run_02.png"),
    include_bytes!("run_03.png"),
    include_bytes!("run_04.png"),
    include_bytes!("run_05.png"),
    include_bytes!("run_06.png"),
    include_bytes!("run_07.png"),
    include_bytes!("run_08.png"),
    include_bytes!("run_09.png"),
    include_bytes!("run_10.png"),
    include_bytes!("run_11.png"),
    include_bytes!("run_12.png"),
    include_bytes!("run_13.png"),
    include_bytes!("run_14.png"),
    include_bytes!("run_15.png"),
    include_bytes!("run_16.png"),
    include_bytes!("run_17.png"),
    include_bytes!("run_18.png"),
    include_bytes!("run_19.png"),
    include_bytes!("run_20.png"),
    include_bytes!("run_21.png"),
    include_bytes!("run_22.png"),
    include_bytes!("run_23.png"),
];
const ATTACK_PNG: [&[u8]; 10] = [
    include_bytes!("attack_00.png"),
    include_bytes!("attack_01.png"),
    include_bytes!("attack_02.png"),
    include_bytes!("attack_03.png"),
    include_bytes!("attack_04.png"),
    include_bytes!("attack_05.png"),
    include_bytes!("attack_06.png"),
    include_bytes!("attack_07.png"),
    include_bytes!("attack_08.png"),
    include_bytes!("attack_09.png"),
];
